### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by ACuteWoof** [Neeraj029/Python-tutorial-for-beginner#1]

**Comment by Neeraj029** [comment]
Oh lol, almost forgot about this 😅

**Comment by ACuteWoof** [comment]
> Oh lol, almost forgot about this sweat_smile I'll try to complete this in few days

I'd love to help if we can have some sort of place to communicate :)

**Comment by ACuteWoof** [comment]
![image](https://user-images.githubusercontent.com/63534975/153700854-6cbca676-6952-4495-88c4-63c4e2a805ed.png)
And for this, this is your repo lol you don't have to say sorry. I'm doing good but missing you so much

**Comment by Neeraj029** [comment]
> And for this, this is your repo lol you don't have to say sorry.
:grinning:

> but missing you so much
Same here :pleading_face:  I think I'll be back in next month.

**Comment by ACuteWoof** [comment]
> Same here pleading_face I think I'll be back in next month.

Oh I'll be waiting
